apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: broker1
spec:
  acceptors:
    - name: acceptor
      port: 61616
      protocols: amqp,mqtt
      expose: true
  console:
    expose: true
  deploymentPlan:
    image: placeholder
    size: 1
    requireLogin: false
    persistenceEnabled: true
    journalType: aio
    messageMigration: false
    jolokiaAgentEnabled: false
    managementRBACEnabled: true
    clustered: false
  adminUser: admin
  adminPassword: admin

